baseURL = 'http://localhost/pruebahugo'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'tale'
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 2
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 3
